services:
  app_wo_ssh:
    build: .
    init: true
    tty: true
    ports:
      - 8080:8080
    volumes:
      - repo:/home/node/umur-table
  sonarqube:
    image: sonarqube
    init: true
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - 9000:9000
  sonar_scanner:
    image: sonarsource/sonar-scanner-cli
    init: true
    depends_on:
      - sonarqube
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_SCANNER_OPTS=-Dsonar.projectKey=override-this-value-in-docker-compose.override.yml
      - SONAR_LOGIN=override-this-value-in-docker-compose.override.yml
    volumes:
      - repo:/usr/src
volumes:
  repo:
